title: Modern Cryptography
description: Modern Cryptography Course
theme: just-the-docs

url: https://bupthpc.github.io/modern-cryptography

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true

# # Aux links for the upper right navigation
# aux_links:
#   "Home":
#     - "/"

# # Makes Aux links open in a new tab. Default is false
# aux_links_new_tab: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red